version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  app:
    build:
      context: .
      args:
        - RAILS_ENV=development
    volumes:
      - "build:/app/.build"
      - "vendor:/app/vendor"
      - "node_modules:/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - MYSQL_HOST=db
    depends_on:
      - db

  test:
    build:
      context: .
      args:
        - RAILS_ENV=test
    volumes:
      - "build:/app/.build"
      - "vendor:/app/vendor"
      - "node_modules:/app/node_modules"
      - ./spec/:/app/spec
    command: ["bundle", "exec", "rspec"]
    environment:
      - RAILS_ENV=test
      - MYSQL_HOST=db
    depends_on:
      - db

volumes: 
  build: 
  vendor:
  node_modules: